package com.cbg.scrapy.service.dal.entity;

import java.util.Date;

public class ScrapyAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scrapy_account_info.id
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scrapy_account_info.account
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scrapy_account_info.password
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scrapy_account_info.status
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scrapy_account_info.add_time
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scrapy_account_info.update_time
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scrapy_account_info.id
     *
     * @return the value of scrapy_account_info.id
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scrapy_account_info.id
     *
     * @param id the value for scrapy_account_info.id
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scrapy_account_info.account
     *
     * @return the value of scrapy_account_info.account
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scrapy_account_info.account
     *
     * @param account the value for scrapy_account_info.account
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scrapy_account_info.password
     *
     * @return the value of scrapy_account_info.password
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scrapy_account_info.password
     *
     * @param password the value for scrapy_account_info.password
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scrapy_account_info.status
     *
     * @return the value of scrapy_account_info.status
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scrapy_account_info.status
     *
     * @param status the value for scrapy_account_info.status
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scrapy_account_info.add_time
     *
     * @return the value of scrapy_account_info.add_time
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scrapy_account_info.add_time
     *
     * @param addTime the value for scrapy_account_info.add_time
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scrapy_account_info.update_time
     *
     * @return the value of scrapy_account_info.update_time
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scrapy_account_info.update_time
     *
     * @param updateTime the value for scrapy_account_info.update_time
     *
     * @mbg.generated Tue Mar 04 22:42:22 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}