package com.cbg.scrapy.service.dal.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.id
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.url
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.role_name
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.sales_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private BigDecimal salesPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.user_first_counter_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private BigDecimal userFirstCounterPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.user_first_counter_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private Date userFirstCounterTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.user_latest_follow_up_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private BigDecimal userLatestFollowUpPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.current_buyer_highest_counter_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private BigDecimal currentBuyerHighestCounterPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.current_buyer_highest_reject_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private BigDecimal currentBuyerHighestRejectPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.operate_status
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private Integer operateStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.user_comment
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private String userComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.highest_reject_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private Date highestRejectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.add_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.update_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_info.md5
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    private String md5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.id
     *
     * @return the value of task_info.id
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.id
     *
     * @param id the value for task_info.id
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.url
     *
     * @return the value of task_info.url
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.url
     *
     * @param url the value for task_info.url
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.role_name
     *
     * @return the value of task_info.role_name
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.role_name
     *
     * @param roleName the value for task_info.role_name
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.sales_price
     *
     * @return the value of task_info.sales_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public BigDecimal getSalesPrice() {
        return salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.sales_price
     *
     * @param salesPrice the value for task_info.sales_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setSalesPrice(BigDecimal salesPrice) {
        this.salesPrice = salesPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.user_first_counter_price
     *
     * @return the value of task_info.user_first_counter_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public BigDecimal getUserFirstCounterPrice() {
        return userFirstCounterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.user_first_counter_price
     *
     * @param userFirstCounterPrice the value for task_info.user_first_counter_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setUserFirstCounterPrice(BigDecimal userFirstCounterPrice) {
        this.userFirstCounterPrice = userFirstCounterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.user_first_counter_time
     *
     * @return the value of task_info.user_first_counter_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public Date getUserFirstCounterTime() {
        return userFirstCounterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.user_first_counter_time
     *
     * @param userFirstCounterTime the value for task_info.user_first_counter_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setUserFirstCounterTime(Date userFirstCounterTime) {
        this.userFirstCounterTime = userFirstCounterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.user_latest_follow_up_price
     *
     * @return the value of task_info.user_latest_follow_up_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public BigDecimal getUserLatestFollowUpPrice() {
        return userLatestFollowUpPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.user_latest_follow_up_price
     *
     * @param userLatestFollowUpPrice the value for task_info.user_latest_follow_up_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setUserLatestFollowUpPrice(BigDecimal userLatestFollowUpPrice) {
        this.userLatestFollowUpPrice = userLatestFollowUpPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.current_buyer_highest_counter_price
     *
     * @return the value of task_info.current_buyer_highest_counter_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public BigDecimal getCurrentBuyerHighestCounterPrice() {
        return currentBuyerHighestCounterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.current_buyer_highest_counter_price
     *
     * @param currentBuyerHighestCounterPrice the value for task_info.current_buyer_highest_counter_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setCurrentBuyerHighestCounterPrice(BigDecimal currentBuyerHighestCounterPrice) {
        this.currentBuyerHighestCounterPrice = currentBuyerHighestCounterPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.current_buyer_highest_reject_price
     *
     * @return the value of task_info.current_buyer_highest_reject_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public BigDecimal getCurrentBuyerHighestRejectPrice() {
        return currentBuyerHighestRejectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.current_buyer_highest_reject_price
     *
     * @param currentBuyerHighestRejectPrice the value for task_info.current_buyer_highest_reject_price
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setCurrentBuyerHighestRejectPrice(BigDecimal currentBuyerHighestRejectPrice) {
        this.currentBuyerHighestRejectPrice = currentBuyerHighestRejectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.operate_status
     *
     * @return the value of task_info.operate_status
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public Integer getOperateStatus() {
        return operateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.operate_status
     *
     * @param operateStatus the value for task_info.operate_status
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setOperateStatus(Integer operateStatus) {
        this.operateStatus = operateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.user_comment
     *
     * @return the value of task_info.user_comment
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public String getUserComment() {
        return userComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.user_comment
     *
     * @param userComment the value for task_info.user_comment
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setUserComment(String userComment) {
        this.userComment = userComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.highest_reject_time
     *
     * @return the value of task_info.highest_reject_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public Date getHighestRejectTime() {
        return highestRejectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.highest_reject_time
     *
     * @param highestRejectTime the value for task_info.highest_reject_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setHighestRejectTime(Date highestRejectTime) {
        this.highestRejectTime = highestRejectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.add_time
     *
     * @return the value of task_info.add_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.add_time
     *
     * @param addTime the value for task_info.add_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.update_time
     *
     * @return the value of task_info.update_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.update_time
     *
     * @param updateTime the value for task_info.update_time
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info.md5
     *
     * @return the value of task_info.md5
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info.md5
     *
     * @param md5 the value for task_info.md5
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setMd5(String md5) {
        this.md5 = md5;
    }
}