package com.cbg.scrapy.service.dal.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public TaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNull() {
            addCriterion("role_name is null");
            return (Criteria) this;
        }

        public Criteria andRoleNameIsNotNull() {
            addCriterion("role_name is not null");
            return (Criteria) this;
        }

        public Criteria andRoleNameEqualTo(String value) {
            addCriterion("role_name =", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotEqualTo(String value) {
            addCriterion("role_name <>", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThan(String value) {
            addCriterion("role_name >", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("role_name >=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThan(String value) {
            addCriterion("role_name <", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLessThanOrEqualTo(String value) {
            addCriterion("role_name <=", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameLike(String value) {
            addCriterion("role_name like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotLike(String value) {
            addCriterion("role_name not like", value, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameIn(List<String> values) {
            addCriterion("role_name in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotIn(List<String> values) {
            addCriterion("role_name not in", values, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameBetween(String value1, String value2) {
            addCriterion("role_name between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andRoleNameNotBetween(String value1, String value2) {
            addCriterion("role_name not between", value1, value2, "roleName");
            return (Criteria) this;
        }

        public Criteria andSalesPriceIsNull() {
            addCriterion("sales_price is null");
            return (Criteria) this;
        }

        public Criteria andSalesPriceIsNotNull() {
            addCriterion("sales_price is not null");
            return (Criteria) this;
        }

        public Criteria andSalesPriceEqualTo(Long value) {
            addCriterion("sales_price =", value, "salesPrice");
            return (Criteria) this;
        }

        public Criteria andSalesPriceNotEqualTo(Long value) {
            addCriterion("sales_price <>", value, "salesPrice");
            return (Criteria) this;
        }

        public Criteria andSalesPriceGreaterThan(Long value) {
            addCriterion("sales_price >", value, "salesPrice");
            return (Criteria) this;
        }

        public Criteria andSalesPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("sales_price >=", value, "salesPrice");
            return (Criteria) this;
        }

        public Criteria andSalesPriceLessThan(Long value) {
            addCriterion("sales_price <", value, "salesPrice");
            return (Criteria) this;
        }

        public Criteria andSalesPriceLessThanOrEqualTo(Long value) {
            addCriterion("sales_price <=", value, "salesPrice");
            return (Criteria) this;
        }

        public Criteria andSalesPriceIn(List<Long> values) {
            addCriterion("sales_price in", values, "salesPrice");
            return (Criteria) this;
        }

        public Criteria andSalesPriceNotIn(List<Long> values) {
            addCriterion("sales_price not in", values, "salesPrice");
            return (Criteria) this;
        }

        public Criteria andSalesPriceBetween(Long value1, Long value2) {
            addCriterion("sales_price between", value1, value2, "salesPrice");
            return (Criteria) this;
        }

        public Criteria andSalesPriceNotBetween(Long value1, Long value2) {
            addCriterion("sales_price not between", value1, value2, "salesPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceIsNull() {
            addCriterion("user_first_counter_price is null");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceIsNotNull() {
            addCriterion("user_first_counter_price is not null");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceEqualTo(BigDecimal value) {
            addCriterion("user_first_counter_price =", value, "userFirstCounterPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceNotEqualTo(BigDecimal value) {
            addCriterion("user_first_counter_price <>", value, "userFirstCounterPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceGreaterThan(BigDecimal value) {
            addCriterion("user_first_counter_price >", value, "userFirstCounterPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("user_first_counter_price >=", value, "userFirstCounterPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceLessThan(BigDecimal value) {
            addCriterion("user_first_counter_price <", value, "userFirstCounterPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("user_first_counter_price <=", value, "userFirstCounterPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceIn(List<BigDecimal> values) {
            addCriterion("user_first_counter_price in", values, "userFirstCounterPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceNotIn(List<BigDecimal> values) {
            addCriterion("user_first_counter_price not in", values, "userFirstCounterPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("user_first_counter_price between", value1, value2, "userFirstCounterPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("user_first_counter_price not between", value1, value2, "userFirstCounterPrice");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeIsNull() {
            addCriterion("user_first_counter_time is null");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeIsNotNull() {
            addCriterion("user_first_counter_time is not null");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeEqualTo(Date value) {
            addCriterion("user_first_counter_time =", value, "userFirstCounterTime");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeNotEqualTo(Date value) {
            addCriterion("user_first_counter_time <>", value, "userFirstCounterTime");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeGreaterThan(Date value) {
            addCriterion("user_first_counter_time >", value, "userFirstCounterTime");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("user_first_counter_time >=", value, "userFirstCounterTime");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeLessThan(Date value) {
            addCriterion("user_first_counter_time <", value, "userFirstCounterTime");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeLessThanOrEqualTo(Date value) {
            addCriterion("user_first_counter_time <=", value, "userFirstCounterTime");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeIn(List<Date> values) {
            addCriterion("user_first_counter_time in", values, "userFirstCounterTime");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeNotIn(List<Date> values) {
            addCriterion("user_first_counter_time not in", values, "userFirstCounterTime");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeBetween(Date value1, Date value2) {
            addCriterion("user_first_counter_time between", value1, value2, "userFirstCounterTime");
            return (Criteria) this;
        }

        public Criteria andUserFirstCounterTimeNotBetween(Date value1, Date value2) {
            addCriterion("user_first_counter_time not between", value1, value2, "userFirstCounterTime");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceIsNull() {
            addCriterion("user_latest_follow_up_price is null");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceIsNotNull() {
            addCriterion("user_latest_follow_up_price is not null");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceEqualTo(BigDecimal value) {
            addCriterion("user_latest_follow_up_price =", value, "userLatestFollowUpPrice");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceNotEqualTo(BigDecimal value) {
            addCriterion("user_latest_follow_up_price <>", value, "userLatestFollowUpPrice");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceGreaterThan(BigDecimal value) {
            addCriterion("user_latest_follow_up_price >", value, "userLatestFollowUpPrice");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("user_latest_follow_up_price >=", value, "userLatestFollowUpPrice");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceLessThan(BigDecimal value) {
            addCriterion("user_latest_follow_up_price <", value, "userLatestFollowUpPrice");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("user_latest_follow_up_price <=", value, "userLatestFollowUpPrice");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceIn(List<BigDecimal> values) {
            addCriterion("user_latest_follow_up_price in", values, "userLatestFollowUpPrice");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceNotIn(List<BigDecimal> values) {
            addCriterion("user_latest_follow_up_price not in", values, "userLatestFollowUpPrice");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("user_latest_follow_up_price between", value1, value2, "userLatestFollowUpPrice");
            return (Criteria) this;
        }

        public Criteria andUserLatestFollowUpPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("user_latest_follow_up_price not between", value1, value2, "userLatestFollowUpPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceIsNull() {
            addCriterion("current_buyer_highest_counter_price is null");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceIsNotNull() {
            addCriterion("current_buyer_highest_counter_price is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceEqualTo(BigDecimal value) {
            addCriterion("current_buyer_highest_counter_price =", value, "currentBuyerHighestCounterPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceNotEqualTo(BigDecimal value) {
            addCriterion("current_buyer_highest_counter_price <>", value, "currentBuyerHighestCounterPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceGreaterThan(BigDecimal value) {
            addCriterion("current_buyer_highest_counter_price >", value, "currentBuyerHighestCounterPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("current_buyer_highest_counter_price >=", value, "currentBuyerHighestCounterPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceLessThan(BigDecimal value) {
            addCriterion("current_buyer_highest_counter_price <", value, "currentBuyerHighestCounterPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("current_buyer_highest_counter_price <=", value, "currentBuyerHighestCounterPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceIn(List<BigDecimal> values) {
            addCriterion("current_buyer_highest_counter_price in", values, "currentBuyerHighestCounterPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceNotIn(List<BigDecimal> values) {
            addCriterion("current_buyer_highest_counter_price not in", values, "currentBuyerHighestCounterPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_buyer_highest_counter_price between", value1, value2, "currentBuyerHighestCounterPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestCounterPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_buyer_highest_counter_price not between", value1, value2, "currentBuyerHighestCounterPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceIsNull() {
            addCriterion("current_buyer_highest_reject_price is null");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceIsNotNull() {
            addCriterion("current_buyer_highest_reject_price is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceEqualTo(BigDecimal value) {
            addCriterion("current_buyer_highest_reject_price =", value, "currentBuyerHighestRejectPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceNotEqualTo(BigDecimal value) {
            addCriterion("current_buyer_highest_reject_price <>", value, "currentBuyerHighestRejectPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceGreaterThan(BigDecimal value) {
            addCriterion("current_buyer_highest_reject_price >", value, "currentBuyerHighestRejectPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("current_buyer_highest_reject_price >=", value, "currentBuyerHighestRejectPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceLessThan(BigDecimal value) {
            addCriterion("current_buyer_highest_reject_price <", value, "currentBuyerHighestRejectPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("current_buyer_highest_reject_price <=", value, "currentBuyerHighestRejectPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceIn(List<BigDecimal> values) {
            addCriterion("current_buyer_highest_reject_price in", values, "currentBuyerHighestRejectPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceNotIn(List<BigDecimal> values) {
            addCriterion("current_buyer_highest_reject_price not in", values, "currentBuyerHighestRejectPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_buyer_highest_reject_price between", value1, value2, "currentBuyerHighestRejectPrice");
            return (Criteria) this;
        }

        public Criteria andCurrentBuyerHighestRejectPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("current_buyer_highest_reject_price not between", value1, value2, "currentBuyerHighestRejectPrice");
            return (Criteria) this;
        }

        public Criteria andOperateStatusIsNull() {
            addCriterion("operate_status is null");
            return (Criteria) this;
        }

        public Criteria andOperateStatusIsNotNull() {
            addCriterion("operate_status is not null");
            return (Criteria) this;
        }

        public Criteria andOperateStatusEqualTo(Integer value) {
            addCriterion("operate_status =", value, "operateStatus");
            return (Criteria) this;
        }

        public Criteria andOperateStatusNotEqualTo(Integer value) {
            addCriterion("operate_status <>", value, "operateStatus");
            return (Criteria) this;
        }

        public Criteria andOperateStatusGreaterThan(Integer value) {
            addCriterion("operate_status >", value, "operateStatus");
            return (Criteria) this;
        }

        public Criteria andOperateStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("operate_status >=", value, "operateStatus");
            return (Criteria) this;
        }

        public Criteria andOperateStatusLessThan(Integer value) {
            addCriterion("operate_status <", value, "operateStatus");
            return (Criteria) this;
        }

        public Criteria andOperateStatusLessThanOrEqualTo(Integer value) {
            addCriterion("operate_status <=", value, "operateStatus");
            return (Criteria) this;
        }

        public Criteria andOperateStatusIn(List<Integer> values) {
            addCriterion("operate_status in", values, "operateStatus");
            return (Criteria) this;
        }

        public Criteria andOperateStatusNotIn(List<Integer> values) {
            addCriterion("operate_status not in", values, "operateStatus");
            return (Criteria) this;
        }

        public Criteria andOperateStatusBetween(Integer value1, Integer value2) {
            addCriterion("operate_status between", value1, value2, "operateStatus");
            return (Criteria) this;
        }

        public Criteria andOperateStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("operate_status not between", value1, value2, "operateStatus");
            return (Criteria) this;
        }

        public Criteria andUserCommentIsNull() {
            addCriterion("user_comment is null");
            return (Criteria) this;
        }

        public Criteria andUserCommentIsNotNull() {
            addCriterion("user_comment is not null");
            return (Criteria) this;
        }

        public Criteria andUserCommentEqualTo(String value) {
            addCriterion("user_comment =", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentNotEqualTo(String value) {
            addCriterion("user_comment <>", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentGreaterThan(String value) {
            addCriterion("user_comment >", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentGreaterThanOrEqualTo(String value) {
            addCriterion("user_comment >=", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentLessThan(String value) {
            addCriterion("user_comment <", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentLessThanOrEqualTo(String value) {
            addCriterion("user_comment <=", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentLike(String value) {
            addCriterion("user_comment like", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentNotLike(String value) {
            addCriterion("user_comment not like", value, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentIn(List<String> values) {
            addCriterion("user_comment in", values, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentNotIn(List<String> values) {
            addCriterion("user_comment not in", values, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentBetween(String value1, String value2) {
            addCriterion("user_comment between", value1, value2, "userComment");
            return (Criteria) this;
        }

        public Criteria andUserCommentNotBetween(String value1, String value2) {
            addCriterion("user_comment not between", value1, value2, "userComment");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeIsNull() {
            addCriterion("highest_reject_time is null");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeIsNotNull() {
            addCriterion("highest_reject_time is not null");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeEqualTo(Date value) {
            addCriterion("highest_reject_time =", value, "highestRejectTime");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeNotEqualTo(Date value) {
            addCriterion("highest_reject_time <>", value, "highestRejectTime");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeGreaterThan(Date value) {
            addCriterion("highest_reject_time >", value, "highestRejectTime");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("highest_reject_time >=", value, "highestRejectTime");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeLessThan(Date value) {
            addCriterion("highest_reject_time <", value, "highestRejectTime");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeLessThanOrEqualTo(Date value) {
            addCriterion("highest_reject_time <=", value, "highestRejectTime");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeIn(List<Date> values) {
            addCriterion("highest_reject_time in", values, "highestRejectTime");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeNotIn(List<Date> values) {
            addCriterion("highest_reject_time not in", values, "highestRejectTime");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeBetween(Date value1, Date value2) {
            addCriterion("highest_reject_time between", value1, value2, "highestRejectTime");
            return (Criteria) this;
        }

        public Criteria andHighestRejectTimeNotBetween(Date value1, Date value2) {
            addCriterion("highest_reject_time not between", value1, value2, "highestRejectTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Date value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Date value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Date value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Date value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Date value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Date> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Date> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Date value1, Date value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Date value1, Date value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andMd5IsNull() {
            addCriterion("md5 is null");
            return (Criteria) this;
        }

        public Criteria andMd5IsNotNull() {
            addCriterion("md5 is not null");
            return (Criteria) this;
        }

        public Criteria andMd5EqualTo(String value) {
            addCriterion("md5 =", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotEqualTo(String value) {
            addCriterion("md5 <>", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5GreaterThan(String value) {
            addCriterion("md5 >", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5GreaterThanOrEqualTo(String value) {
            addCriterion("md5 >=", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5LessThan(String value) {
            addCriterion("md5 <", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5LessThanOrEqualTo(String value) {
            addCriterion("md5 <=", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5Like(String value) {
            addCriterion("md5 like", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotLike(String value) {
            addCriterion("md5 not like", value, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5In(List<String> values) {
            addCriterion("md5 in", values, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotIn(List<String> values) {
            addCriterion("md5 not in", values, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5Between(String value1, String value2) {
            addCriterion("md5 between", value1, value2, "md5");
            return (Criteria) this;
        }

        public Criteria andMd5NotBetween(String value1, String value2) {
            addCriterion("md5 not between", value1, value2, "md5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_info
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 01 17:09:18 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table task_info
     *
     * @mbg.generated Sat Mar 01 17:09:18 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}